# Generated by Django 4.1.7 on 2023-03-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleswork', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semibase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NSM', models.CharField(max_length=550)),
                ('RSM', models.CharField(max_length=550)),
                ('ASM', models.CharField(max_length=550)),
                ('REP', models.CharField(default='null', max_length=550)),
                ('REGION', models.CharField(max_length=550)),
                ('CHANNEL', models.CharField(max_length=550)),
                ('GROUP', models.CharField(max_length=3550)),
                ('TEAM', models.CharField(max_length=550)),
                ('CODE', models.CharField(max_length=450)),
                ('STATUS', models.CharField(max_length=550)),
            ],
        ),
    ]
