# Generated by Django 4.1.7 on 2023-03-17 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saleswork', '0002_semibase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledgerbase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LEDGER', models.CharField(max_length=1500)),
                ('SEMICODE', models.CharField(max_length=1500)),
                ('TEAM', models.CharField(max_length=1500)),
                ('STATUS', models.CharField(max_length=1500)),
                ('CODED', models.CharField(max_length=1500)),
                ('semi', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saleswork.semibase')),
            ],
        ),
    ]
