# Generated by Django 4.1.7 on 2023-03-17 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saleswork', '0003_ledgerbase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledgerbase',
            old_name='CODED',
            new_name='GROUP',
        ),
        migrations.RemoveField(
            model_name='ledgerbase',
            name='SEMICODE',
        ),
    ]
