# Generated by Django 4.1.7 on 2023-03-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleswork', '0005_alter_ledgerbase_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1500)),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
