# Generated by Django 4.1.7 on 2023-03-17 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saleswork', '0006_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GROUP', models.CharField(max_length=500)),
                ('TEAM', models.CharField(max_length=500)),
                ('Product', models.CharField(max_length=500)),
                ('value', models.IntegerField()),
                ('procode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saleswork.product')),
                ('semi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saleswork.semibase')),
            ],
        ),
    ]
