# Generated by Django 4.1.7 on 2023-03-17 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saleswork', '0007_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='current',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Money', models.IntegerField()),
                ('TEAM', models.CharField(max_length=500)),
                ('product', models.CharField(max_length=1500)),
                ('customers', models.CharField(max_length=500)),
                ('month', models.IntegerField()),
                ('ctns', models.IntegerField()),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saleswork.ledgerbase')),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saleswork.product')),
            ],
        ),
    ]
