# Generated by Django 4.1.7 on 2023-03-17 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saleswork', '0008_current'),
    ]

    operations = [
        migrations.DeleteModel(
            name='current',
        ),
    ]
