# Generated by Django 4.1.7 on 2023-03-25 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saleswork', '0012_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Name', models.CharField(max_length=500)),
                ('Amount', models.IntegerField()),
                ('month', models.IntegerField()),
                ('fyear', models.IntegerField()),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saleswork.ledgerbase')),
            ],
        ),
    ]
