# Generated by Django 4.1.7 on 2023-03-28 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saleswork', '0015_alter_collection_month'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
