# Generated by Django 4.1.7 on 2023-03-28 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saleswork', '0017_prevcollection_collection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrevCollection',
        ),
    ]
