# Generated by Django 4.1.7 on 2023-03-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleswork', '0019_prevcollection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Opening', models.DateField()),
                ('Closing', models.DateField()),
            ],
        ),
    ]
