# Generated by Django 4.1.7 on 2023-03-29 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saleswork', '0020_period'),
    ]

    operations = [
        migrations.DeleteModel(
            name='current',
        ),
    ]
