# Generated by Django 4.1.7 on 2023-04-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleswork', '0022_previous_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='semibase',
            name='SEGMENT',
            field=models.CharField(choices=[('Trade', 'Trade'), ('Marketing', 'Marketing')], default='Marketing', max_length=150),
        ),
    ]
