# Generated by Django 4.1.7 on 2023-04-11 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saleswork', '0023_semibase_segment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semibase',
            name='CODE',
        ),
    ]
