# Generated by Django 4.1.7 on 2023-04-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleswork', '0024_remove_semibase_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ctnqty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='semibase',
            name='condition',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=150),
        ),
    ]
