# Generated by Django 4.1.7 on 2023-04-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleswork', '0025_product_ctnqty_semibase_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='value',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='current',
            name='fyear',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
