# Generated by Django 4.1.7 on 2023-06-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleswork', '0027_alter_budget_value_alter_current_ctns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semibase',
            name='Target',
            field=models.IntegerField(default=0),
        ),
    ]
